---
apiVersion: v1
kind: Service
metadata:
  name: media-backend-service
spec:
  selector:
    app: media-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30317
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-backend
  labels:
    app: media-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-backend
  template:
    metadata:
      labels:
        app: media-backend
    spec:
      containers:
        - name: media-backend
          image: hamstershare/hamster-media:${hamster_media_version}
          imagePullPolicy: Always
          env:
            - name: EMAIL_PASSWORD
              value: vbxvulwytjyevqhh
            - name: EMAIL_FROM
              value: hamster@hamsternet.io
            - name: EMAIL_TO
              value: bingjian.wang@tntlinking.com haijiang.mo@tntlinking.com alvis@hamsternet.io
            - name: MYSQL_DATABASE
              value: media
            - name: MYSQL_USER
              value: aline
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: '3306'
          ports:
            - containerPort: 8888
